[build]
  base = "frontend"
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NEXT_TELEMETRY_DISABLED = "1"

# API proxy redirect
[[redirects]]
  from = "/api/*"
  to = "https://farm2fork-api.onrender.com/api/:splat"
  status = 200
  force = true

# Handle Next.js SPA routing - all paths go to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
