[build]
  base = "frontend"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# API proxy redirect
[[redirects]]
  from = "/api/*"
  to = "https://farm2fork-api.onrender.com/api/:splat"
  status = 200
  force = true

# Handle Next.js routing - this is the critical part for preventing 404s
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Next.js asset handling
[[headers]]
  for = "/_next/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
